### PR TITLE
major rehaul

### PR DESCRIPTION
**Pull request by nsheff**
huge rehaul on... just about everything.

Not finished, but at a decent stopping point.

### CODE REVIEW

**Comment by nsheff** [comment]
@vreuter I figure if we're gonna do it, let's just do it...

**Comment by vreuter** [comment]
Do we want to do anything special (like maybe keyword argument) for something like file extension in a place like `dirOut`, or keep it as simple as possible? Alternatively, there could be some argument inspection within the function to see if something appears to be an extension. Say, if an argument is the last one in the input list, and it begins with a ".", it could be interpreted as a file extension. I'm also fine with assuming/requiring each argument element to be a true path component, though.

The reason for asking is this sort of thing:
```
project.init::dirOut("explore/pca_", outputTag, ".pdf")
aged_mice_rrbs/analysis/explore/pca_/eucl5K/.pdf
```
There's a call in the EwS project similar to that, which I think would probably result in something similar. If something like an `extension` parameter were provided in the signature, or if the sort of inspection-and-inference scheme suggested were used, we could simply paste the last two elements together before calling `file.path`. Again, though, I'm also fine with requiring that sort of thing to be done on the user side, before the call is ever made.

**Comment by nsheff** [comment]
the problem is the change from `paste` to `file.path`, which is adding that slash... and which, I realized, doesn't even solve the duplicate slashes thing (see [here](https://stackoverflow.com/questions/45619522/preventing-duplicate-slashes-in-file-paths-in-r)). So switching back to `paste0` might be the answer...

**Comment by vreuter** [comment]
I see the main benefit of  `file.path` as being platform-agnostic (I think, anyway) to path component delimiter, and freeing me from the need to provide the slash in the arguments. It's not terrible if I'm passing in all raw character values, but when variables are involved, I don't want to have to remember what does or doesn't have a slash.

**Comment by nsheff** [comment]
Yeah, got it. makes sense. Well for now I guess we can use:

`project.init::dirOut(paste0("explore/pca_", outputTag, ".pdf"))`

we can use `file.path(paste0(...))` instead. but then you have to handle your own slashes.

my typical use case is to use paste0 here and not file.path, since I'm not passing folders, but just a filename I intend to merge together. if I'm passing folders it's like you are: "explore/blah.pdf".

**Comment by nsheff** [comment]
put another way: the slash-handling feature of file.path is negated anyway in your example since you're sticking a slash in the string... so there's no advantage to using `file.path` is there?

**Comment by vreuter** [comment]
Yeah sorry, my point was less about my example and more about existing calls to `dirout`, in EwS or elsewhere. I just went with this for mine:
```
filename = sprintf("pca_%s.pdf", outputTag)
plotPath = project.init::dirOut("explore", filename)
```

I'm just saying that I think it makes a ton of sense to inspect the last element for a leading `.` suggestive that it represents an extension, so that existing calls don't need to change, and since the implementation cost is super minimal. I think in general, it seems more likely that someone would pass a complete filename as the last component and therefore be fine with the current implementation; it's just that there's easy protection for existing uses if we check out that last input argument.

**Comment by nsheff** [comment]
but what about 
```
project.init::dirOut("explore/pca_", outputTag, "_all.pdf")
```
For this reason I don't want to go down the route of trying to guess based on file extension... how about this way:
```file.path(getOption(var), paste0(...))```
This solves all my use cases but I guess not yours. But for your use case I use the subdir mode (`setOutputSubdir`)

I don't think it's possible to have it both ways...

**Comment by nsheff** [comment]
The way I have implemented it now works like this:

```
 dirOut("test", "blah.pdf")
[1] "/sfs/lustre/allocations/shefflab/processed//kipnis_rrbs/analysis/testblah.pdf"
> dirOut(sub="test", "blah.pdf")
[1] "/sfs/lustre/allocations/shefflab/processed//kipnis_rrbs/analysis/test/blah.pdf"
```

does that seem acceptable?

**Comment by vreuter** [comment]
Sure that's fine, I'm likely to `file.path`-together any & all of my non-`option` / non-env-var components anyhow. It could be confusing for anyone used to `file.path` behavior to have each element be glued together without a path separator, but probably plenty of people are wary of that sort of thing.

**Comment by vreuter** [comment]
Whoa...you beat me to the :fist_oncoming:

**Comment by vreuter** [comment]
Yeah sure then no need to differentiate sample/suffix/etc. with named parameters.

**Comment by nsheff** [comment]
can also do:
```
> setOutputSubdir("test")
> dirOut("blah.pdf")
[1] "/sfs/lustre/allocations/shefflab/processed//kipnis_rrbs/analysis/test/blah.pdf"
```

**Comment by nsheff** [comment]
so essentially, we're assuming any parameters you give should represent the file name, so we paste them together. if you want subfolders, you handle that on your own or you can use the subdir functionality.

**Comment by vreuter** [comment]
Yeah that makes sense

**Pull request merged**
